# Generated by Django 4.2.2 on 2023-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME COMPLETO', models.CharField(max_length=150)),
                ('DATA DE NASCIMENTO', models.DataField(max_length=100)),
                ('CPF', models.IntegerField()),
                ('RG', models.IntegerField()),
                ('ORGÃO EXP/ RG PACINETE', models.CharField()),
                ('NIS', models.CharField()),
                ('CID', models.CharField()),
                ('MEDICO SOLICITANTE', models.CharField()),
                ('CNS', models.CharField()),
                ('IDADE', models.CharField()),
                ('SEXO', models.CharField()),
                ('RAÇA/COR', models.CharField()),
                ('ADMISSÃO', models.CharField()),
                ('ENDEREÇO', models.CharField()),
                ('CODIGO DE LOGRADOURO', models.CharField()),
                ('Nº DA CASA', models.CharField()),
                ('COMPLEMENTO', models.CharField()),
                ('BAIRRO', models.CharField()),
                ('MUNICÍPIO', models.CharField()),
                ('ESTADO CIVIL', models.CharField()),

                ('NOME DA MÃE', models.CharField()),
                ('CPF MÃE', models.CharField()),
                ('RG DA MÃE', models.CharField()),
                ('RG SSP MÃE', models.CharField()),
                ('NIS/MÃE', models.CharField()),
                ('NOME DO PAI', models.CharField()),
                ('CPF PAI', models.CharField()),
                ('RG PAI', models.CharField()),
                ('RG SSP PAI', models.CharField()),
                ('TELEFONE BPA', models.CharField()),
                ('TELEFONE ADICIONAL', models.CharField()),
                ('TELEFONE 3', models.CharField()),
                ('RESPONSÁVEL', models.CharField()),
                ('DOC RESPONSÁVEL CPF', models.CharField()),
                ('RG RESPONSÁVEL', models.CharField()),
                ('ORGÃO EXP RESPONSÁVEL', models.CharField()),

            ],
        ),
    ]
