# Generated by Django 4.2.3 on 2023-07-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='demanda_global',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='cns',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='register',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='register',
            name='orgao_exp_rg_paciente',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='register',
            name='rg',
            field=models.CharField(max_length=10),
        ),
    ]
