# Generated by Django 4.2.2 on 2023-06-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_marca_carros_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='idade',
            field=models.CharField(max_length=100),
        ),
    ]
