from django.db import models

# Create your models here.
class Carros(models.Model):
    NOME_COMPLETO = models.CharField(max_length=100)
    DATA_DE_NASCIMENTO = models.DataField
    CPF = models.IntegerField()
    RG = models.IntegerField()
    ORGÃO_EXP_RG_PACINETE = models.CharField()
    NIS = models.CharField()
    CID = models.CharField()
    MEDICO_SOLICITANTE = models.CharField()
    CNS = models.CharField()
    IDADE = models.CharField()
    SEXO = models.CharField()
    RAÇA_COR = models.CharField()
    ADMISSÃO = models.CharField()
    ENDEREÇO = models.CharField()
    CODIGO_DE_LOGRADOURO = models.CharField()
    Nº_DA_CASA = models.CharField()
    COMPLEMENTO = models.CharField()
    BAIRRO = models.CharField()
    MUNICÍPIO = models.CharField()
    ESTADO_CIVIL = models.CharField()
    NOME_DA_MÃE = models.CharField()
    CPF_MÃE = models.CharField()
    RG_DA_MÃE = models.CharField()
    RG_SSP_MÃE = models.CharField()
    NIS_MÃE = models.CharField()
    NOME_DO_PAI = models.CharField()
    CPF_PAI = models.CharField()
    RG_PAI = models.CharField()
    RG_SSP_PAI = models.CharField()
    TELEFONE_BPA = models.CharField()
    TELEFONE_ADICIONAL = models.CharField()
    TELEFONE_3 = models.CharField()
    RESPONSÁVEL = models.CharField()
    DOC_RESPONSÁVEL_CPF = models.CharField()
    RG_RESPONSÁVEL = models.CharField()
    ORGÃO_EXP_RESPONSÁVEL = models.CharField()