from django.db import models
# from django import forms


# Create your models here.
class Register(models.Model):
    nome_completo = models.CharField(max_length=100)
    data_de_nascimento = models.DateField(max_length=100)
    cpf = models.CharField(max_length=100)
    rg = models.CharField(max_length=100)
    orgao_exp_rg_paciente = models.CharField(max_length=100)
    nis = models.CharField(max_length=100)
    cid = models.CharField(max_length=100)
    medico_solicitante = models.CharField(max_length=100)
    cns = models.CharField(max_length=100)
    idade = models.IntegerField()
    sexo = models.CharField(max_length=100)
    raca_cor = models.CharField(max_length=100)
    admissao = models.CharField(max_length=100)
    endereco = models.CharField(max_length=100)
    codigo_de_logradrouro = models.CharField(max_length=100)
    n_da_casa = models.CharField(max_length=100)
    complemento = models.CharField(max_length=100)
    bairro = models.CharField(max_length=100)
    municipio = models.CharField(max_length=100)
    estado_civil = models.CharField(max_length=100)
    nome_da_mae = models.CharField(max_length=100)
    cpf_mae = models.CharField(max_length=100)
    rg_da_mae = models.CharField(max_length=100)
    rg_ssp_mae = models.CharField(max_length=100)
    nis_mae = models.CharField(max_length=100)
    nome_do_pai = models.CharField(max_length=100)
    cpf_pai = models.CharField(max_length=100)
    rg_pai = models.CharField(max_length=100)
    rg_ssp_pai = models.CharField(max_length=100)
    telefone_bpa = models.CharField(max_length=100)
    telefone_principal = models.CharField(max_length=100)
    telefone_adicional = models.CharField(max_length=100)
    responsavel = models.CharField(max_length=100)
    doc_responsavel_cpf = models.CharField(max_length=100)
    rg_responsavel = models.CharField(max_length=100)
    orgao_exp_responsavel = models.CharField(max_length=100)
